#!/usr/bin/env python3
"""Regenerate MEGATIDE's fixed-point lookup-table source files.

The generated tables are deliberately checked into both source trees so neither
avr-gcc nor Arduino builds require Python. This script exists to document the
numeric design and make future range changes reproducible.
"""

from __future__ import annotations

import math
from pathlib import Path

F_CPU = 16_000_000
PRESCALER = 8
PWM_COUNTS = 256
SERVICE_HZ = F_CPU / PRESCALER / PWM_COUNTS

ROOT = Path(__file__).resolve().parents[1]
TARGETS = (
    ROOT / "avr-gcc" / "src" / "tables.c",
    ROOT / "arduino" / "MEGATIDE" / "tables.cpp",
)


def format_values(values: list[int], per_line: int, suffix: str) -> str:
    lines: list[str] = []
    for start in range(0, len(values), per_line):
        group = values[start : start + per_line]
        comma = "," if start + per_line < len(values) else ""
        lines.append("    " + ", ".join(f"{value}{suffix}" for value in group) + comma)
    return "\n".join(lines)


def build_source() -> str:
    sine = [
        round((math.sin(2.0 * math.pi * index / 256.0) + 1.0) * 127.5)
        for index in range(256)
    ]

    rate: list[int] = []
    for index in range(256):
        frequency = 0.01 * (100.0 / 0.01) ** (index / 255.0)
        increment = round((2**32) * frequency / SERVICE_HZ)
        rate.append(max(1, min(0xFFFFFFFF, increment)))

    envelope: list[int] = []
    for index in range(256):
        duration = 0.001 * (30.0 / 0.001) ** (index / 255.0)
        ticks = max(1, round(duration * SERVICE_HZ))
        step = round(0xFFFF0000 / ticks)
        envelope.append(max(1, min(0xFFFF0000, step)))

    return f'''#include "tables.h"

#include <avr/pgmspace.h>

/* Generated by tools/generate_tables.py. Do not hand-edit table values. */

static const uint8_t g_sine_table[256] PROGMEM =
{{
{format_values(sine, 16, "u")}
}};

static const uint32_t g_rate_increment_table[256] PROGMEM =
{{
{format_values(rate, 4, "UL")}
}};

static const uint32_t g_envelope_step_table[256] PROGMEM =
{{
{format_values(envelope, 4, "UL")}
}};

uint8_t mt_table_sine_u8(uint8_t index)
{{
    return pgm_read_byte(&g_sine_table[index]);
}}

uint32_t mt_table_rate_increment(uint8_t index)
{{
    return pgm_read_dword(&g_rate_increment_table[index]);
}}

uint32_t mt_table_envelope_step(uint8_t index)
{{
    return pgm_read_dword(&g_envelope_step_table[index]);
}}
'''


def main() -> None:
    source = build_source()
    for target in TARGETS:
        target.write_text(source, encoding="utf-8")
        print(f"wrote {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
